input_csv: ../Data/Processed/test_predictions_medfair_ready.csv

label_column: True_Label
prediction_column: Pred_Label

group_columns:
  - Age_Group
# Uncomment these if available in your CSV:
#  - Race
#  - Menopausal_Status
#  - Scanner
#  - Vendor

output_dir: ../Outputs/Reports

metrics:
  - accuracy
  - f1
  - roc_auc

plot_disparities: true
